export function normalizeGoal<T extends Record<string, unknown>>(goal: T): T & { iterations: unknown[] };
export function nextCriterionId(existing?: Array<{ id: string }>): string;
export function normalizeCriteriaInputs(inputs: unknown[], existing?: Array<{ id: string }>): unknown[];
export function appendUniqueStrings(existing?: unknown[], incoming?: unknown[], maxItems?: number): string[];
export function mergeCriteria(existing?: unknown[], proposed?: unknown[], updates?: unknown[]): unknown[];
export function blockedStatusFromReport(report: unknown, policy?: Record<string, unknown>): { blocked: boolean; reason?: string };
export function waitingStatusFromReport(report: unknown, policy?: Record<string, unknown>): { waiting: boolean; reason?: string };
export function recommendScaffoldId(objective?: string): string;
export function buildGoalContextPacket(goal: unknown, scaffold?: unknown, request?: Record<string, unknown>): unknown;
export function goalAgentReportEffectiveOutcome(report: unknown, policy?: Record<string, unknown>): unknown;
export function criteriaInputsFromGoalAgentReport(report: unknown): { proposed: unknown[]; updates: unknown[] };
export function applyGoalAgentReport(goal: unknown, report: unknown, scaffold?: unknown, options?: { now?: string }): unknown;
export function applyGoalReviewerReport(goal: unknown, report: unknown, options?: { now?: string }): unknown;
export function applyCriterionUpdates(criteria: unknown[], updates: unknown[]): unknown[];
export function validateReview(review: unknown): void;
export function completionReadiness(goal: unknown): { ready: boolean; missing: string[] };
export function validateGoalAgentReport(report: unknown): unknown;
export function formatEvidenceRef(evidence: unknown): string;
export function formatEvidenceRefs(items?: unknown[]): string[];
